//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankWS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiResponse", Namespace="http://tempuri.org/")]
    public partial class ApiResponse : object
    {
        
        private string ResponseCodeField;
        
        private string ResponseDescriptionField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseDescription
        {
            get
            {
                return this.ResponseDescriptionField;
            }
            set
            {
                this.ResponseDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://tempuri.org/")]
    public partial class Client : object
    {
        
        private int ClientIDField;
        
        private string NameField;
        
        private string DNIField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ClientID
        {
            get
            {
                return this.ClientIDField;
            }
            set
            {
                this.ClientIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DNI
        {
            get
            {
                return this.DNIField;
            }
            set
            {
                this.DNIField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccount", Namespace="http://tempuri.org/")]
    public partial class BankAccount : object
    {
        
        private int AccountIDField;
        
        private BankWS.Transaction[] TransactionHistoryField;
        
        private double BalanceField;
        
        private BankWS.Client AccountOwnerField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AccountID
        {
            get
            {
                return this.AccountIDField;
            }
            set
            {
                this.AccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public BankWS.Transaction[] TransactionHistory
        {
            get
            {
                return this.TransactionHistoryField;
            }
            set
            {
                this.TransactionHistoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Balance
        {
            get
            {
                return this.BalanceField;
            }
            set
            {
                this.BalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public BankWS.Client AccountOwner
        {
            get
            {
                return this.AccountOwnerField;
            }
            set
            {
                this.AccountOwnerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://tempuri.org/")]
    public partial class Transaction : object
    {
        
        private int TransactionIDField;
        
        private string DescriptionField;
        
        private System.DateTime DateField;
        
        private double AmountField;
        
        private BankWS.TransactionType TransactionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TransactionID
        {
            get
            {
                return this.TransactionIDField;
            }
            set
            {
                this.TransactionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public BankWS.TransactionType TransactionType
        {
            get
            {
                return this.TransactionTypeField;
            }
            set
            {
                this.TransactionTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionType", Namespace="http://tempuri.org/")]
    public enum TransactionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Received = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Submitted = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Null = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankWS.BankAPISoap")]
    public interface BankAPISoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Name del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewClient", ReplyAction="*")]
        BankWS.AddNewClientResponse AddNewClient(BankWS.AddNewClientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewClient", ReplyAction="*")]
        System.Threading.Tasks.Task<BankWS.AddNewClientResponse> AddNewClientAsync(BankWS.AddNewClientRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento AddNewAccountResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewAccount", ReplyAction="*")]
        BankWS.AddNewAccountResponse AddNewAccount(BankWS.AddNewAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<BankWS.AddNewAccountResponse> AddNewAccountAsync(BankWS.AddNewAccountRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetClientsResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClients", ReplyAction="*")]
        BankWS.GetClientsResponse GetClients(BankWS.GetClientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetClients", ReplyAction="*")]
        System.Threading.Tasks.Task<BankWS.GetClientsResponse> GetClientsAsync(BankWS.GetClientsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAccountsResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccounts", ReplyAction="*")]
        BankWS.GetAccountsResponse GetAccounts(BankWS.GetAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccounts", ReplyAction="*")]
        System.Threading.Tasks.Task<BankWS.GetAccountsResponse> GetAccountsAsync(BankWS.GetAccountsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAccountResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccount", ReplyAction="*")]
        BankWS.GetAccountResponse GetAccount(BankWS.GetAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<BankWS.GetAccountResponse> GetAccountAsync(BankWS.GetAccountRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sourceAccount del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MakeTransaction", ReplyAction="*")]
        BankWS.MakeTransactionResponse MakeTransaction(BankWS.MakeTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MakeTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<BankWS.MakeTransactionResponse> MakeTransactionAsync(BankWS.MakeTransactionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewClientRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewClient", Namespace="http://tempuri.org/", Order=0)]
        public BankWS.AddNewClientRequestBody Body;
        
        public AddNewClientRequest()
        {
        }
        
        public AddNewClientRequest(BankWS.AddNewClientRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewClientRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DNI;
        
        public AddNewClientRequestBody()
        {
        }
        
        public AddNewClientRequestBody(string Name, string DNI)
        {
            this.Name = Name;
            this.DNI = DNI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewClientResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewClientResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankWS.AddNewClientResponseBody Body;
        
        public AddNewClientResponse()
        {
        }
        
        public AddNewClientResponse(BankWS.AddNewClientResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewClientResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankWS.ApiResponse AddNewClientResult;
        
        public AddNewClientResponseBody()
        {
        }
        
        public AddNewClientResponseBody(BankWS.ApiResponse AddNewClientResult)
        {
            this.AddNewClientResult = AddNewClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewAccount", Namespace="http://tempuri.org/", Order=0)]
        public BankWS.AddNewAccountRequestBody Body;
        
        public AddNewAccountRequest()
        {
        }
        
        public AddNewAccountRequest(BankWS.AddNewAccountRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewAccountRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ClientID;
        
        public AddNewAccountRequestBody()
        {
        }
        
        public AddNewAccountRequestBody(int ClientID)
        {
            this.ClientID = ClientID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankWS.AddNewAccountResponseBody Body;
        
        public AddNewAccountResponse()
        {
        }
        
        public AddNewAccountResponse(BankWS.AddNewAccountResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewAccountResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankWS.ApiResponse AddNewAccountResult;
        
        public AddNewAccountResponseBody()
        {
        }
        
        public AddNewAccountResponseBody(BankWS.ApiResponse AddNewAccountResult)
        {
            this.AddNewAccountResult = AddNewAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClients", Namespace="http://tempuri.org/", Order=0)]
        public BankWS.GetClientsRequestBody Body;
        
        public GetClientsRequest()
        {
        }
        
        public GetClientsRequest(BankWS.GetClientsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetClientsRequestBody
    {
        
        public GetClientsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClientsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClientsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankWS.GetClientsResponseBody Body;
        
        public GetClientsResponse()
        {
        }
        
        public GetClientsResponse(BankWS.GetClientsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetClientsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankWS.Client[] GetClientsResult;
        
        public GetClientsResponseBody()
        {
        }
        
        public GetClientsResponseBody(BankWS.Client[] GetClientsResult)
        {
            this.GetClientsResult = GetClientsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccounts", Namespace="http://tempuri.org/", Order=0)]
        public BankWS.GetAccountsRequestBody Body;
        
        public GetAccountsRequest()
        {
        }
        
        public GetAccountsRequest(BankWS.GetAccountsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAccountsRequestBody
    {
        
        public GetAccountsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankWS.GetAccountsResponseBody Body;
        
        public GetAccountsResponse()
        {
        }
        
        public GetAccountsResponse(BankWS.GetAccountsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankWS.BankAccount[] GetAccountsResult;
        
        public GetAccountsResponseBody()
        {
        }
        
        public GetAccountsResponseBody(BankWS.BankAccount[] GetAccountsResult)
        {
            this.GetAccountsResult = GetAccountsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccount", Namespace="http://tempuri.org/", Order=0)]
        public BankWS.GetAccountRequestBody Body;
        
        public GetAccountRequest()
        {
        }
        
        public GetAccountRequest(BankWS.GetAccountRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AccountID;
        
        public GetAccountRequestBody()
        {
        }
        
        public GetAccountRequestBody(int AccountID)
        {
            this.AccountID = AccountID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankWS.GetAccountResponseBody Body;
        
        public GetAccountResponse()
        {
        }
        
        public GetAccountResponse(BankWS.GetAccountResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankWS.BankAccount GetAccountResult;
        
        public GetAccountResponseBody()
        {
        }
        
        public GetAccountResponseBody(BankWS.BankAccount GetAccountResult)
        {
            this.GetAccountResult = GetAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakeTransactionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakeTransaction", Namespace="http://tempuri.org/", Order=0)]
        public BankWS.MakeTransactionRequestBody Body;
        
        public MakeTransactionRequest()
        {
        }
        
        public MakeTransactionRequest(BankWS.MakeTransactionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MakeTransactionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankWS.BankAccount sourceAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int targetAccountID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string description;
        
        public MakeTransactionRequestBody()
        {
        }
        
        public MakeTransactionRequestBody(BankWS.BankAccount sourceAccount, int targetAccountID, double amount, string description)
        {
            this.sourceAccount = sourceAccount;
            this.targetAccountID = targetAccountID;
            this.amount = amount;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakeTransactionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakeTransactionResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankWS.MakeTransactionResponseBody Body;
        
        public MakeTransactionResponse()
        {
        }
        
        public MakeTransactionResponse(BankWS.MakeTransactionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MakeTransactionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankWS.ApiResponse MakeTransactionResult;
        
        public MakeTransactionResponseBody()
        {
        }
        
        public MakeTransactionResponseBody(BankWS.ApiResponse MakeTransactionResult)
        {
            this.MakeTransactionResult = MakeTransactionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface BankAPISoapChannel : BankWS.BankAPISoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class BankAPISoapClient : System.ServiceModel.ClientBase<BankWS.BankAPISoap>, BankWS.BankAPISoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BankAPISoapClient(EndpointConfiguration endpointConfiguration) : 
                base(BankAPISoapClient.GetBindingForEndpoint(endpointConfiguration), BankAPISoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankAPISoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BankAPISoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankAPISoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BankAPISoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankWS.AddNewClientResponse BankWS.BankAPISoap.AddNewClient(BankWS.AddNewClientRequest request)
        {
            return base.Channel.AddNewClient(request);
        }
        
        public BankWS.ApiResponse AddNewClient(string Name, string DNI)
        {
            BankWS.AddNewClientRequest inValue = new BankWS.AddNewClientRequest();
            inValue.Body = new BankWS.AddNewClientRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.DNI = DNI;
            BankWS.AddNewClientResponse retVal = ((BankWS.BankAPISoap)(this)).AddNewClient(inValue);
            return retVal.Body.AddNewClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankWS.AddNewClientResponse> BankWS.BankAPISoap.AddNewClientAsync(BankWS.AddNewClientRequest request)
        {
            return base.Channel.AddNewClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankWS.AddNewClientResponse> AddNewClientAsync(string Name, string DNI)
        {
            BankWS.AddNewClientRequest inValue = new BankWS.AddNewClientRequest();
            inValue.Body = new BankWS.AddNewClientRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.DNI = DNI;
            return ((BankWS.BankAPISoap)(this)).AddNewClientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankWS.AddNewAccountResponse BankWS.BankAPISoap.AddNewAccount(BankWS.AddNewAccountRequest request)
        {
            return base.Channel.AddNewAccount(request);
        }
        
        public BankWS.ApiResponse AddNewAccount(int ClientID)
        {
            BankWS.AddNewAccountRequest inValue = new BankWS.AddNewAccountRequest();
            inValue.Body = new BankWS.AddNewAccountRequestBody();
            inValue.Body.ClientID = ClientID;
            BankWS.AddNewAccountResponse retVal = ((BankWS.BankAPISoap)(this)).AddNewAccount(inValue);
            return retVal.Body.AddNewAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankWS.AddNewAccountResponse> BankWS.BankAPISoap.AddNewAccountAsync(BankWS.AddNewAccountRequest request)
        {
            return base.Channel.AddNewAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankWS.AddNewAccountResponse> AddNewAccountAsync(int ClientID)
        {
            BankWS.AddNewAccountRequest inValue = new BankWS.AddNewAccountRequest();
            inValue.Body = new BankWS.AddNewAccountRequestBody();
            inValue.Body.ClientID = ClientID;
            return ((BankWS.BankAPISoap)(this)).AddNewAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankWS.GetClientsResponse BankWS.BankAPISoap.GetClients(BankWS.GetClientsRequest request)
        {
            return base.Channel.GetClients(request);
        }
        
        public BankWS.Client[] GetClients()
        {
            BankWS.GetClientsRequest inValue = new BankWS.GetClientsRequest();
            inValue.Body = new BankWS.GetClientsRequestBody();
            BankWS.GetClientsResponse retVal = ((BankWS.BankAPISoap)(this)).GetClients(inValue);
            return retVal.Body.GetClientsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankWS.GetClientsResponse> BankWS.BankAPISoap.GetClientsAsync(BankWS.GetClientsRequest request)
        {
            return base.Channel.GetClientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankWS.GetClientsResponse> GetClientsAsync()
        {
            BankWS.GetClientsRequest inValue = new BankWS.GetClientsRequest();
            inValue.Body = new BankWS.GetClientsRequestBody();
            return ((BankWS.BankAPISoap)(this)).GetClientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankWS.GetAccountsResponse BankWS.BankAPISoap.GetAccounts(BankWS.GetAccountsRequest request)
        {
            return base.Channel.GetAccounts(request);
        }
        
        public BankWS.BankAccount[] GetAccounts()
        {
            BankWS.GetAccountsRequest inValue = new BankWS.GetAccountsRequest();
            inValue.Body = new BankWS.GetAccountsRequestBody();
            BankWS.GetAccountsResponse retVal = ((BankWS.BankAPISoap)(this)).GetAccounts(inValue);
            return retVal.Body.GetAccountsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankWS.GetAccountsResponse> BankWS.BankAPISoap.GetAccountsAsync(BankWS.GetAccountsRequest request)
        {
            return base.Channel.GetAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankWS.GetAccountsResponse> GetAccountsAsync()
        {
            BankWS.GetAccountsRequest inValue = new BankWS.GetAccountsRequest();
            inValue.Body = new BankWS.GetAccountsRequestBody();
            return ((BankWS.BankAPISoap)(this)).GetAccountsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankWS.GetAccountResponse BankWS.BankAPISoap.GetAccount(BankWS.GetAccountRequest request)
        {
            return base.Channel.GetAccount(request);
        }
        
        public BankWS.BankAccount GetAccount(int AccountID)
        {
            BankWS.GetAccountRequest inValue = new BankWS.GetAccountRequest();
            inValue.Body = new BankWS.GetAccountRequestBody();
            inValue.Body.AccountID = AccountID;
            BankWS.GetAccountResponse retVal = ((BankWS.BankAPISoap)(this)).GetAccount(inValue);
            return retVal.Body.GetAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankWS.GetAccountResponse> BankWS.BankAPISoap.GetAccountAsync(BankWS.GetAccountRequest request)
        {
            return base.Channel.GetAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankWS.GetAccountResponse> GetAccountAsync(int AccountID)
        {
            BankWS.GetAccountRequest inValue = new BankWS.GetAccountRequest();
            inValue.Body = new BankWS.GetAccountRequestBody();
            inValue.Body.AccountID = AccountID;
            return ((BankWS.BankAPISoap)(this)).GetAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankWS.MakeTransactionResponse BankWS.BankAPISoap.MakeTransaction(BankWS.MakeTransactionRequest request)
        {
            return base.Channel.MakeTransaction(request);
        }
        
        public BankWS.ApiResponse MakeTransaction(BankWS.BankAccount sourceAccount, int targetAccountID, double amount, string description)
        {
            BankWS.MakeTransactionRequest inValue = new BankWS.MakeTransactionRequest();
            inValue.Body = new BankWS.MakeTransactionRequestBody();
            inValue.Body.sourceAccount = sourceAccount;
            inValue.Body.targetAccountID = targetAccountID;
            inValue.Body.amount = amount;
            inValue.Body.description = description;
            BankWS.MakeTransactionResponse retVal = ((BankWS.BankAPISoap)(this)).MakeTransaction(inValue);
            return retVal.Body.MakeTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankWS.MakeTransactionResponse> BankWS.BankAPISoap.MakeTransactionAsync(BankWS.MakeTransactionRequest request)
        {
            return base.Channel.MakeTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankWS.MakeTransactionResponse> MakeTransactionAsync(BankWS.BankAccount sourceAccount, int targetAccountID, double amount, string description)
        {
            BankWS.MakeTransactionRequest inValue = new BankWS.MakeTransactionRequest();
            inValue.Body = new BankWS.MakeTransactionRequestBody();
            inValue.Body.sourceAccount = sourceAccount;
            inValue.Body.targetAccountID = targetAccountID;
            inValue.Body.amount = amount;
            inValue.Body.description = description;
            return ((BankWS.BankAPISoap)(this)).MakeTransactionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BankAPISoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BankAPISoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BankAPISoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:62102/BankAPI.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.BankAPISoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:62102/BankAPI.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BankAPISoap,
            
            BankAPISoap12,
        }
    }
}
